services:
  mist-server-dev:
    image: ghcr.io/coral-land/atoll-mistserver-docker:latest-amd64
    restart: unless-stopped
    entrypoint: ["sleep", "infinity"]
    init: true
    ports:
      - "4242:4242"
      - "1935:1935"
      - "8080:8080"
      - "554:554"
      - "10000-10005:10000-10005/udp" # SRT/RIST (Example range)
    volumes:
      - ./config:/config
      - ./media:/media:ro
    environment:
      - TZ=UTC
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
